# Generated by Django 3.0 on 2019-12-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_updated',
        ),
    ]
