# Generated by Django 3.0 on 2019-12-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_last_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flag_dict',
            new_name='Filter_Words',
        ),
    ]
