# Generated by Django 3.0 on 2019-12-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191209_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_type',
        ),
    ]
